services:
  cads-mis:
    build:
      target: development
    image: cads-mis-development
    container_name: cads-mis-test
    command: npm run test
    env_file:
      - path: .env
        required: false
    environment:
      PORT: 3000
      REDIS_HOST: cads-redis
    volumes:
      - ./src/:/home/node/src
      - ./test/:/home/node/test
      - ./package.json:/home/node/package.json
    networks:
      - cads-tools

networks:
  cads-tools:
    external: true